### ISSUE TITLE
RuntimeError: PyArray_GetArrayParamsFromObject() C-API function is removed

### ISSUE THREAD

**Issue by thomasahle** [FALCONN-LIB/FFHT#30]
I installed FFHT with Python 3.9 and got this error when trying to run `example.py`:
    
    $ py example.py
    Traceback (most recent call last):
      File "/Users/ahle/Dropbox (Meta)/kode/ts/FFHT/example.py", line 14, in <module>
        ffht.fht(a)
    RuntimeError: PyArray_GetArrayParamsFromObject() C-API function is removed `PyArray_FromAny()` should be used at this time.  New C-API may be exposed in the future (please do request this if it would help you).

I'm on numpy version 1.21.3.

The API seems to have been depriated in 1.19: https://numpy.org/devdocs/release/1.19.0-notes.html#deprecation-of-probably-unused-c-api-functions

**Comment by Synia-L** [comment]
Hello, I encountered the same problem as you. Did you solve the problem by dropping the numpy version below 1.19? I dropped to 1.18 and then prompted：`ImportError: numpy.core.multiarray failed to import`

**Comment by Synia-L** [comment]
> I installed FFHT with Python 3.9 and got this error when trying to run `example.py`:
> 
> ```
> $ py example.py
> Traceback (most recent call last):
>   File "/Users/ahle/Dropbox (Meta)/kode/ts/FFHT/example.py", line 14, in <module>
>     ffht.fht(a)
> RuntimeError: PyArray_GetArrayParamsFromObject() C-API function is removed `PyArray_FromAny()` should be used at this time.  New C-API may be exposed in the future (please do request this if it would help you).
> ```
> 
> I'm on numpy version 1.21.3.
> 
> The API seems to have been depriated in 1.19: https://numpy.org/devdocs/release/1.19.0-notes.html#deprecation-of-probably-unused-c-api-functions

Hello, I encountered the same problem as you. Did you solve the problem by dropping the numpy version below 1.19? I dropped to 1.18 and then prompted：`ImportError: numpy.core.multiarray failed to import`

**Comment by dnbaker** [comment]
I addressed this in a fork - https://github.com/dnbaker/ffht.

I switched to pybind11 to remove the deprecated api usage and added 2d support.
